expt_config:
  dataset:
    name: "Cora"
  batch_size: 64
  logging_config:
    use_wandb: True
    wandb_config:
      log_model: False
      group: "base"
      job_type: "tune"

  dataset_dir: "/users/$USER/conformal-fairness/datasets"
  resource_config:
    gpus: 1
    cpus: 27
  num_workers: 25
  epochs: 10
n_trials_per_config: 5

l_types: ["GCN", "GAT", "GraphSAGE"]
tune_split_config:
  s_type: "split"
  samples_per_class: [10, 20]
  train_fracs: [0.2, 0.3]
  val_fracs: [0.1, 0.2]

tune_output_dir: "./tune_results"
num_samples: 10
